Changements for v0.0.2
njam/nuxt-i18n-module pull request #1
Opened 2017-12-06 16:38 UTC by orblazer

Implement NuxtI18nLink component, improve detection of language and implement option for default language

2018-03-30 15:49 UTC, njam requested changes
@orblazer very sorry to only get back to you about this now...
Are you still interested in getting this merged?

@christopheschwyzer maybe you want to take a look too?

2018-03-30 15:49 UTC, njam commented on README.md
> +- `defaultLanguage` : The default language ***⚠ Required: The value need defined in `languages`***
How about making it optional? We could just use the first language as the default. That way we keep the configuration backwards compatible.

2018-03-30 15:49 UTC, njam commented on src/templates/plugin.js
> +  Vue.availableLanguages = Object.keys(messages)
What's the reason to get the *available languages* from the messages/phrases, and not from the module config (`options.languages`)? I think it'd be good to do it consistently across the module, and the latter seems a more robust source for that, wdyt?

2018-03-30 18:20 UTC, orblazer commented
Yex, i go apply the changes in next days

2018-07-03 15:25 UTC, orblazer commented
Hello, i have remake my PR for the last version and with better code.

The PR is here : #16

2018-07-03 15:25 UTC, closed without merging